insert into USER_DETAILS(USER_ID,USER_NAME,PASSWORD,ACTIVE, ROLE)
values(1, 'anil','$2a$10$LjXHSif9ZrMgPRcJ/0Q5FOMR7ZTz2VkqfzI87j3XvQ0UTcMTLkGBi',1, 'ROLE_USER');
insert into USER_DETAILS(USER_ID,USER_NAME,PASSWORD,ACTIVE, ROLE)
values(2, 'bandari','$2a$10$tcFXBgUvdN47m8Pzdc0JbOoxCM9BsHtEpc/v9xSqRSNprgzESTlyi',1, 'ROLE_USER,ROLE_ADMIN');